<?php
// $Id: xoops_version.php,v 1.1 2005/07/10 02:32:17 mauriciodelima Exp $
//  ------------------------------------------------------------------------ //
//              RM+SOFT - Systema de Ayuda y Manuales en Línea               //
//                Copyright RM+SOFT © 2005. (Eduardo Cortés)                 //
//                     <http://www.redmexico.com.mx/>                        //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//  ------------------------------------------------------------------------ //
//	Este programa es un programa libre; puedes distribuirlo y modificarlo	 //
//	bajo los términos de al GNU General Public Licencse como ha sido		 //
//	publicada por The Free Software Foundation (Fundación de Software Libre; //
//	en cualquier versión 2 de la Licencia o mas reciente.					 //
//                                                                           //
//	Este programa es distribuido esperando que sea últil pero SIN NINGUNA	 //
//	GARANTÍA. Ver The GNU General Public License para mas detalles.			 //
//  ------------------------------------------------------------------------ //
//	Questions, Bugs or any comment plese write me						 	 //
//	Preguntas, errores o cualquier comentario escribeme						 //
//	<adminone@redmexico.com.mx>												 //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _MI_RMLIB_NAME;
$modversion['version'] = 1.5;
$modversion['description'] = _MI_RMLIB_DESC;
$modversion['author'] = "AdminOne <http://www.redmexico.com.mx>";
$modversion['credits'] = "AdminOne";
$modversion['help'] = "";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/logo.png";
$modversion['dirname'] = "rmlib";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "rmlib_temas";
$modversion['tables'][1] = "rmlib_indice";
$modversion['tables'][2] = "rmlib_contenido";
$modversion['tables'][3] = "rmlib_categos";
$modversion['tables'][4] = "rmlib_users";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['hasMain'] = 1;

// Blocks
$modversion['blocks'][1]['file'] = "rmlib_sections.php";
$modversion['blocks'][1]['name'] = _MI_RMLIB_BNAME1;
$modversion['blocks'][1]['description'] = "Muestra 5 secciones de la biblioteca";
$modversion['blocks'][1]['show_func'] = "b_rmlib_sections_show";
$modversion['blocks'][1]['edit_func'] = "";
$modversion['blocks'][1]['options'] = "";
$modversion['blocks'][1]['template'] = 'rmlib_block_sections.html';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "rmlib_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'index';
$modversion['comments']['pageName'] = 'content.php';
$modversion['comments']['extraParams'] = array('comid');

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comments.php';
$modversion['comments']['callback']['approve'] = 'rmlib_com_approve';
$modversion['comments']['callback']['update'] = 'rmlib_com_update';

// Templates
$modversion['templates'][1]['file'] = 'rmlib_categos.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'rmlib_temas.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'rmlib_books.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'rmlib_content.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'rmlib_editcontent.html';
$modversion['templates'][5]['description'] = 'Edición del Contenido de los libros';

// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][1]['name'] = 'xoopscode';

// title of this config option displayed in config settings form
$modversion['config'][1]['title'] = '_MI_RMLIB_XOOPSCODE';

// description of this config option displayed under title
$modversion['config'][1]['description'] = '_MI_RMLIB_XOOPSCODEDESC';

// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][1]['formtype'] = 'yesno';

// value type of this config option. can be one of either int, text, float, array, or other
// form type of 'group_multi', 'select_multi' must always be 'array'
// form type of 'yesno', 'group' must be always be 'int'
$modversion['config'][1]['valuetype'] = 'int';

// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
$modversion['config'][1]['default'] = 1;

// options to be displayed in selection box
// required and valid for 'select' or 'select_multi' formtype option only
// language constants can be used for both array keys and values
$modversion['config'][1]['options'] = array('0' => 'No', '1' => 'Si');

/* Nombre de la biblioteca */
$modversion['config'][2]['name'] = 'libname';
$modversion['config'][2]['title'] = '_MI_RMLIB_LIBNAME';
$modversion['config'][2]['description'] = '';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'text';
$modversion['config'][2]['default'] = "Biblioteca de RM+Soft";


?>
